name: espo_crm_client
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fish_redux: ^0.2.8
  common_utils: ^1.1.3
  permission_handler: ^3.3.0
  cached_network_image: ^1.1.3
  shared_preferences: ^0.5.4+3
  toast: ^0.1.5
  url_launcher: ^5.2.5
  retrofit: any
  json_annotation: any
  logger: any  #for logging purpose
  dio_flutter_transformer: ^3.0.2
  percent_indicator: 2.1.1+1
  contacts_service:
    git: https://github.com/akaGelo/flutter_contacts.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: any
  retrofit_generator: any
  build_runner: any
  json_serializable: any


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    #  - images/a_dot_burr.jpeg
    - images/espocrm.png
    - images/CacheBG.jpg
    - images/facebook_circle.png
    - images/twitter_circle.png
    - images/instagram_circle.png
    - images/link_bold.png
    - images/tmdb_blue.png
    - images/yoda.png
    - images/luke_skywalker.png
    - images/darth_vader.png
    - images/chewbacca.png
    - images/c3po.png
    - images/r2d2.png
    - images/google.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
